config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  resources :posts
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  root   'static_pages#home'
  get    '/about',       to: 'static_pages#about'
  get    '/pre_order',   to: 'static_pages#pre_order'
  get    '/concept_art', to: 'static_pages#concept_art'
  get    '/contact',     to: 'static_pages#contact'
  get    '/dev_log',     to: 'posts#index'
  get    '/new_posts',   to: 'posts#new'
  post   '/new_posts',   to: 'posts#create'
  get    '/signup',      to: 'users#new'
  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'
  get 'password_resets/new'
  get 'password_resets/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {maximum: 100}
  validates :body,  presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :delete]

  #index for all posts
  def index
    @posts = Post.all
  end

  #New action for creating posts
  def new
    @post = Post.new
    if logged_in?
      flash[:alert] = "Time for another Dev Update!"
    else
      redirect_to root_url
      flash[:alert] = "Please log in to access post creation."
    end
  end

  #Create action for saving posts
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Your post has been created!"
      redirect_to dev_log_path
    else
      flash[:alert] = "Error creating post. Please try again."
      render :new
    end
  end

  def edit
    if logged_in?
      flash[:alert] = "Editing in progress"
    else
      redirect_to login_path
      flash[:alert] = "You need to be logged in to access editing."
    end
  end

  #update action for posts
  def update
    if @post.update_attributes(post_params)
      #flash notice and redirect
      flash[:notice] = "Post updated! Returning to Posts Index page"
      redirect_to dev_log_path(@posts)
    else
      #flash alert and redirect to edit
      flash[:alert] = "Error updating, UwU my bad."
      render :edit
    end
  end

  def show
  end

  #action for removing posts from db
  def destroy
    if Post.find(params[:id]).destroy
      #flash sucess notice and redirect
      flash[:notice] = "Post sent to gulag."
      redirect_to dev_log_path
    else
      #flash alert
      flash[:alert] = "Error deleting post!"
    end
  end

  private

    #write post parameters
    def post_params
      params.require(:post).permit(:title, :body)
    end

    #action for finding posts
    def find_post
      @post = Post.find(params[:id])
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_postform.html.erb
<!-- This is the posts form, this will be used across the various views -->
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_messages">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being rendered." %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- posts form for title/body/submit-->
  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form_group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2 id="fancy-text"> Edit Post </h2>

<%= render "posts/postform" %>

app/views/posts/index.html.erb
<div class="container blog-bg">
  <div class="col-sm-10 col-sm-offset-1 col-xs-12">
    <% @posts.each do |post| %>
      <div>
        <div class="col-xs-12 text-center" id="fancy-text">
          <div class="text-center">
            <h2><%= post.title %></h2>
            <h6>Post created @ <%= post.created_at.strftime('%b %d, %Y') %></h6>
          </div>
          <div class="text-center">
            <%= link_to "READ MORE", post_path(post) %>
          </div>
          <div>
            <% if logged_in? %>
              <%= link_to "Edit", edit_post_path(post), class: "btn btn-default" %>
              <%= link_to "Delete", post_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h2 id="fancy-text"> New Dev Update </h2>

<%= render "posts/postform" %>

app/views/posts/show.html.erb
<div class="col-sm-11 col-xs-12 blog-bg">
  <h2 class="text-center" id="fancy-text"><%= @post.title %></h2>
  <h5 class="text-center" id="fancy-text"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
  <div id=fancy-text><%= raw @post.body %></div>
</div>